name: Deploy Chatbot

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Run Chatbot Script
      run: node chatbot.js
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
